In [1]:
import pandas as pd
df1=pd.DataFrame()
list1=[i for i in range (1,10)]
list2=[i**2 for i in range (1,10)]
list3=[i**3 for i in range (1,10)]
df1['number']=list1
df1['square']=list2
df1['cube']=list3
df1

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [2]:
df1.columns

Index(['number', 'square', 'cube'], dtype='object')

In [4]:
df1.drop('number',axis=1)

square  cube
0       1     1
1       4     8
2       9    27
3      16    64
4      25   125
5      36   216
6      49   343
7      64   512
8      81   729

In [ ]:
import pandas as ps
df1

**step-9**

**how to select the column**

In [5]:
df1['number']

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: number, dtype: int64

In [6]:
df1['number']

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: number, dtype: int64

In [8]:
type(df1['number'])

pandas.core.series.Series

- df2['number']: series type

- df2[['number']]: dataframe type
    
- df2.number: series type

In [9]:
cols=['number','square']
df1[cols]

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [10]:
df1['number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- all values comes in an array

- array means it is a list of elements only represents using numpy package

- generally elements present in 4 ways

    - list: basic representations
    
    - numpy array: array with numpy package
        
    - tensors: tensoeflow package
        
    - torch: pytorch package

In [11]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [12]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [13]:
tensor([1,2,3,4])

NameError: name 'tensor' is not defined

In [14]:
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [15]:
l1=np.array(list1)
l2=np.array(list2)
l3=l1+l2
l3

array([11, 22, 33, 44])

In [ ]:
# 3 days every day one numpy
# a new package in the market: numpy
# you know python

In [17]:
df1['number'].values
# imagine we worked on an ml problem
# we got some of values
# with that series of values also we can create a datagframe

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [18]:
df1['number']=df1['number'].values
df1

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**step-10**

**save the dataframe**

- dataframe we can save in two formats

    - csv: comma seperated value
    
    - xlsx: excel format

- in order to save any data

    - where you want to save: directory name
        
    - what is the name of the file for storing
    
    - what is the extension
    
- we already seen in file handing session

# case-1

- saving file at same location

- no need to provide directory path

- directly give only name of the file

- and entension

In [19]:
# dataframe name: df1
df1.to_csv()

',number,square,cube\r\n0,1,1,1\r\n1,2,4,8\r\n2,3,9,27\r\n3,4,16,64\r\n4,5,25,125\r\n5,6,36,216\r\n6,7,49,343\r\n7,8,64,512\r\n8,9,81,729\r\n'

In [21]:
# dataframe name
df1.to_csv('data1.csv')
df1.to_excel('data1.xlsx')

**step-11**

**how to read the daraframe**

In [24]:
import pandas as pd
pd.read_csv('data1.csv')

Unnamed: 0  number  square  cube
0           0       1       1     1
1           1       2       4     8
2           2       3       9    27
3           3       4      16    64
4           4       5      25   125
5           5       6      36   216
6           6       7      49   343
7           7       8      64   512
8           8       9      81   729

In [25]:
import pandas as pd
pd.read_excel('data1.xlsx')

Unnamed: 0  number  square  cube
0           0       1       1     1
1           1       2       4     8
2           2       3       9    27
3           3       4      16    64
4           4       5      25   125
5           5       6      36   216
6           6       7      49   343
7           7       8      64   512
8           8       9      81   729

In [ ]:
**step-12**
**how to avoid index column**

- while we save the dataframe

- automatically a 

In [32]:
# dataframe name:df1
# save the data with out index column
df1.to_csv('data1.csv',index=False)
df1.to_excel('data1.xlsx',index=False)

In [29]:
import pandas as pd
pd.read_csv('data1.csv')

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [31]:
# read the data
import pandas as pd
pd.read_excel('data1.xlsx')

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729